title: Nelson Dsouza # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced data scientist with a demonstrated history of working in various industries like Finance, Genomics , Logistics, Enterprise Solutions and more. Driven by solving hard real-world problems and gaining insight from data. Skilled in statistical modelling, machine learning and deep learning with the ability to manage and drive an advanced data science team.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/nelson-d-67350585/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-158383219-1 # your Google Analytics tracking ID here
