title: Nelson Dsouza # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced data scientist with a demonstrated history of working  
  <br><br>
  in various industries like Finance, Genomics, Logistics, Enterprise Solutions and more.
  <br><br> 
  Driven by solving hard real-world problems and gaining insight from data. 
  <br><br>
  Skilled in statistical modelling, machine learning and deep learning with the ability 
  <br><br>
  to manage and drive an advanced data science team.
  <br><br>
  
  <a href="https://www.linkedin.com/in/nelson-d-67350585/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-158383219-1 # your Google Analytics tracking ID here
